# ç‰ˆæœ¬å·
version: "1.0.0"

# æ”¯æŒå¤šç”¨æˆ·ï¼Œæ¯ä¸ªç”¨æˆ·ä¸€ä¸ªé…ç½®
users:
  - name: "å°‘å¥¶å¥¶"
    token: "xxxxx"
    targetChatID: -1234567
    startCmdMessage: "(*ï¿£ï¸¶ï¿£)ğŸ˜Š æ‚¨å¥½ï¼Œæˆ‘åœ¨å‘¢ï¼Œè¯·è¯´... "

  - name: "å°‘çˆ·"
    token: "yyyyy"
    targetChatID: -1234567
    startCmdMessage: "(*ï¿£ï¸¶ï¿£)ğŸ˜Š æ‚¨å¥½ï¼Œæˆ‘åœ¨å‘¢ï¼Œè¯·è¯´... "
